Add a space to homepage to correct typo
railslink/railslink pull request #198
Opened 2021-09-14 22:08 UTC by atayl16

Changes "founders,backend" to "founders, backend" on the main landing page
![ksnip_20210914-230626](https://user-images.githubusercontent.com/24377351/133340461-1e2884ac-27ea-4c2e-a65a-83d8b2704060.png)

2021-09-28 22:53 UTC, grepsedawk requested changes
A lot of editors delete trailing spaces automatically, looks like this is a solution that would allow this to be multiline without trailing spaces:
```p
  | test
    test
#--->
<p>test
test</p>

```

2021-09-29 21:19 UTC, grepsedawk commented on app/views/home/index.html.slim
>          | backend engineers, and people just learning Ruby on Rails.
```suggestion
          including avid OSS contributors, full-stack engineers, startup founders,
          backend engineers, and people just learning Ruby on Rails.
```

2021-09-29 21:56 UTC, atayl16 commented on app/views/home/index.html.slim
>          | backend engineers, and people just learning Ruby on Rails.
Thank you @grepsedawk

2021-09-29 22:19 UTC, grepsedawk commented
Did this work when you tested it?

2021-09-30 19:06 UTC, atayl16 commented
Yes it did :) 
![image](https://user-images.githubusercontent.com/24377351/135515729-7b86cfa5-85fb-457b-8fa4-1574a121f475.png)

2021-09-30 22:59 UTC, grepsedawk approved these changes

2021-09-30 22:59 UTC, merged